import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.scss";
import { videos } from "@/data/videoData";
const merriweather = Merriweather({ subsets: ["latin"], weight: ["400", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const randomIndex = Math.floor(Math.random() * 8);

  return (
    <html lang="en">
      <body className={merriweather.className}>
        <video
          autoPlay
          loop
          muted
          src={Object.values(videos)[randomIndex].videoUrl}
        ></video>
        {children}
      </body>
    </html>
  );
}
